- name: Update Ubuntu
  apt:
    update_cache: yes

- name: Install Python PIP
  apt:
    name: python3-pip

- name: Install Virtualenv
  apt:
    name: python3-venv

- name: Install Python is Python3
  apt:
    name: python-is-python3

- name: Update PIP to Latest Version
  command: pip3 install -U pip

- name: Install NGINX
  apt:
    name: nginx
    state: latest
